=== Manuel-Russo/5c_TPS/XML/magazzino/magazzino.dtd
<!ELEMENT magazzino (articolo*)>
<!ELEMENT articolo (paragrafo+)>
<!ELEMENT paragrafo (testo+, immagine*, codice?)>
<!ELEMENT testo (#PCDATA)>
<!ELEMENT immagine (#PCDATA)>
<!ELEMENT codice (#PCDATA)>

<!ATTLIST articolo
    cod ID #REQUIRED
    titolo CDATA #REQUIRED
    data CDATA #IMPLIED>

<!ATTLIST paragrafo
    titolo CDATA #IMPLIED
    tipo (abstract|bibbliografia|note) #REQUIRED>

=== Manuel-Russo/5c_TPS/XML/magazzino/magazzino.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magazzino SYSTEM "magazzino.dtd">
<magazzino>
    <articolo cod="c1" titolo="" data="">
        <paragrafo titolo="" tipo="abstract">
            <testo></testo>
            <immagine></immagine>
            <immagine></immagine>
            <immagine></immagine>
            <codice></codice>
        </paragrafo>
    </articolo>
    <articolo cod="c2" titolo="">
        <paragrafo titolo="" tipo="note">
            <testo></testo>
            <immagine></immagine>
        </paragrafo>
    </articolo>
</magazzino>
