=== Manuel-Russo/5c_TPS/ARG_XML/XSD/rubrica/rubrica.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--  definizione schema rubrica -->
    <xs:element name="rubrica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contatto" type="info_contatto" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--  definizione tag contatto -->
    <xs:complexType name="info_contatto">
        <xs:sequence>
            <xs:element name="nome" type="xs:string" />
            <xs:element name="cognome" type="xs:string" />
            <xs:element name="indirizzo" type="xs:string" />
            <xs:element name="telefono" minOccurs="1" maxOccurs="4">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>   
            <xs:element name="email" type="xs:string" minOccurs="1" maxOccurs="3"/>
            <!-- <xs:element name="website" type="xs:string" /> -->
            <xs:element name="website">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="url" type="xs:string" use="optional"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>   
           </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Manuel-Russo/5c_TPS/ARG_XML/XSD/rubrica/rubrica.xml
<?xml version="1.0"?>
<rubrica
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="rubrica.xsd">
    <contatto> <!-- complex type -->
        <nome></nome> <!-- simple type -->
        <cognome></cognome>
        <indirizzo></indirizzo>
        <telefono>4567</telefono>
        <telefono>34569</telefono>
        <telefono>678765</telefono>
        <telefono>567876543</telefono>
        <email></email>
        <email></email>
        <email></email>
        <website url="ok">google.com</website>
    </contatto>
    <contatto>
        <nome></nome>
        <cognome></cognome>
        <indirizzo></indirizzo>
        <telefono>13245</telefono>
        <email></email>
        <website></website>
    </contatto>

</rubrica>
