=== Manuel-Russo/5c_TPS/XML/film/film.dtd
<!ELEMENT catalogo (film*)>
<!ELEMENT film (titolo, regista+, attore*, genere?)>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT regista (#PCDATA)>
<!ELEMENT attore (#PCDATA)>
<!ELEMENT genere (#PCDATA)>

<!ATTLIST film
    cod ID #REQUIRED
    originalitÃ  (si|no) "si"
    formato (BD|DVD|STREAMING) #REQUIRED
    voto CDATA #IMPLIED
>

=== Manuel-Russo/5c_TPS/XML/film/film.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "film.dtd">
<catalogo>
    <film cod="primo" originalità="si" formato="DVD" voto="">
        <titolo></titolo>
        <regista></regista>
        <attore></attore>
        <attore></attore>
    </film>
    <film cod="secondo" originalità="si" formato="BD" voto="">
        <titolo></titolo>
        <regista></regista>
        <attore></attore>
        <genere></genere>
    </film>
</catalogo>
