=== Manuel-Russo/5c_TPS/ARG_XML/Esercitazione_finale_Russo/netflix.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="piattaforma">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="video" type="infoFilm" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="infoFilm">
        <xs:sequence>
            <xs:element name="titolo" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="trama" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="500"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="tipologia" type="infoTipologie" minOccurs="1" maxOccurs="1"/>

            <xs:element name="durata" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:integer">
                            <xs:attribute name="unitÃ " use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>

            <xs:element name="linguaAudio" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="risoluzione" type="infoRisoluzione" minOccurs="1" maxOccurs="1"/>

            <xs:element name="numeroLike" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="numeroDislike" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="numeroVisualizzazioni" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="annoCaricamento" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="numeroCommenti" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="numeroCondivisioni" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="infoTipologie">
        <xs:sequence>
            <xs:element name="tipologia">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="film"/>
                        <xs:enumeration value="notiziario"/>
                        <xs:enumeration value="serie"/>
                        <xs:enumeration value="animazione"/>
                        <xs:enumeration value="documentario"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="infoRisoluzione">
        <xs:sequence>
            <xs:element name="risoluzione">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="280p"/>
                        <xs:enumeration value="360p"/>
                        <xs:enumeration value="480p"/>
                        <xs:enumeration value="720p"/>
                        <xs:enumeration value="1080p"/>
                        <xs:enumeration value="4K"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Manuel-Russo/5c_TPS/Esercitazione_finale_Russo/netflix.xml
<?xml version="1.0" encoding="UTF-8"?>
<piattaforma>
    <video xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="netflix.xsd">
        <titolo>Fury</titolo>
        <trama>Storia di soldati americani durante la seconda guerra mondiale in Francia</trama>
        <tipologia>Film</tipologia>
        <durata unitÃ ="minuti">134</durata>
        <linguaAudio>Inglese</linguaAudio>
        <risoluzione>1080</risoluzione>
        <numeroLike>150000</numeroLike>
        <numeroDislike>2000</numeroDislike>
        <numeroVisualizzazioni>1000000</numeroVisualizzazioni>
        <annoCaricamento>2014</annoCaricamento>
        <numeroCommenti>150</numeroCommenti>
        <numeroCondivisioni>20000</numeroCondivisioni>
    </video>
</piattaforma>
