=== Manuel-Russo/5c_TPS/XSD/rubrica/rubrica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rubrica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contatto" type="info_contatto" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="info_contatto">
        <xs:sequence>
            <xs:element name="nome" type="xs:string" />
            <xs:element name="cognome" type="xs:string" />
            <xs:element name="indirizzo" type="xs:string" />
            <xs:element name="telefono" minOccurs="1" maxOccurs="unbounded">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:maxInclusive value="9999999999"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email" type="xs:string" />
            <xs:element name="website" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Manuel-Russo/5c_TPS/XSD/rubrica/rubrica.xml
<?xml version="1.0"?>
<rubrica 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="rubrica.xsd">
        <contatto> <!-- complex type perchÃ¨ all'interno altri tag-->
            <nome></nome> <!-- simple type non ci sono altri tag interni -->
            <cognome></cognome>
            <indirizzo></indirizzo>
            <telefono></telefono>
            <telefono></telefono>
            <telefono></telefono>
            <telefono></telefono>
            <email></email>
            <email></email>
            <email></email>
            <website></website>
        </contatto>
        <contatto>
            <nome></nome>
            <cognome></cognome>
            <indirizzo></indirizzo>
            <telefono></telefono>
            <telefono></telefono>
            <telefono></telefono>
            <telefono></telefono>
            <email></email>
            <email></email>
            <email></email>
            <website></website>
        </contatto>
        <contatto>
            <nome></nome>
            <cognome></cognome>
            <indirizzo></indirizzo>
            <telefono></telefono>
            <telefono></telefono>
            <telefono></telefono>
            <telefono></telefono>
            <email></email>
            <email></email>
            <email></email>
            <website></website>
        </contatto>
</rubrica>
