=== Manuel-Russo/5c_TPS/ParserJava/automobiliRusso/noleggio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="noleggio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="auto" type="info_auto" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="info_auto">
        <xs:sequence>
            <xs:element name="classe">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="A"/>
                        <xs:enumeration value="B"/>
                        <xs:enumeration value="C"/>
                        <xs:enumeration value="D"/>
                        <xs:enumeration value="E"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            
            <xs:element name="marca" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:element>
            
            <xs:element name="modello">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:element>

            <xs:element name="cilindrata">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                            <xs:attribute name="unità" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>

            <xs:element name="potenza">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                            <xs:attribute name="unità" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>

            <xs:element name="alimentazione" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Benzina"/>
                        <xs:enumeration value="Metano"/>
                        <xs:enumeration value="Diesel"/>
                        <xs:enumeration value="Elettrica"/>
                        <xs:enumeration value="Ibrida"/>
                        <xs:enumeration value="GPL"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="numero_passeggieri">
                <xs:simpleType>
                    <xs:restriction base="xs:integer"/>
                </xs:simpleType>
            </xs:element>

            <xs:element name="volume_bagagliaio">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                            <xs:attribute name="unità" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>

        </xs:sequence>
    </xs:complexType>   
</xs:schema>

=== Manuel-Russo/5c_TPS/ParserJava/automobiliRusso/noleggio.xml
<?xml version="1.0"?>
<noleggio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="noleggio.xsd">
    <auto>
        <classe>B</classe>
        <marca>Corvette</marca>
        <modello>C8 Stingray Coupé</modello>
        <cilindrata unità="cm3">1500</cilindrata>
        <potenza unità="Kw">350</potenza>
        <alimentazione>Benzina</alimentazione>
        <numero_passeggieri>2</numero_passeggieri>
        <volume_bagagliaio unità="litri">100</volume_bagagliaio>
    </auto>
</noleggio>
