=== Manuel-Russo/5c_TPS/ARG_XML/Verifica_Russo/XSD/negozio.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="negozio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="prodotto" type="info_prodotto" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="info_prodotto">
        <xs:sequence>
            <xs:element name="categoria" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="audio"/>
                        <xs:enumeration value="video"/>
                        <xs:enumeration value="telefonia"/>
                        <xs:enumeration value="informatica"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="codice" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="15"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="marca" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="15"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="modello" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="15"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="descrizione" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="250"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="prezzo" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:decimal">
                            <xs:attribute name="unità" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>

            <xs:element name="quantità" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Manuel-Russo/5c_TPS/Verifica_Russo/XSD/negozio.xml
<?xml version="1.0" encoding="UTF-8"?>

<negozio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="negozio.xsd">
    <prodotto>
        <categoria>video</categoria>
        <codice>125469</codice>
        <marca>Philips</marca>
        <modello>AO587</modello>
        <descrizione>Tv a schermo piatto ad alta risoluzione</descrizione>
        <prezzo unità="€">290</prezzo>
        <quantità>13</quantità>
    </prodotto>
    <prodotto>
        <categoria>audio</categoria>
        <codice>2185687</codice>
        <marca>Sony</marca>
        <modello>MX87</modello>
        <descrizione>Casse sorround 8.1</descrizione>
        <prezzo unità="€">500</prezzo>
        <quantità>3</quantità>
    </prodotto>
    <prodotto>
        <categoria>telefonia</categoria>
        <codice>54214</codice>
        <marca>Samsung</marca>
        <modello>Flip 4</modello>
        <descrizione>Telefono ribaltabile a conchiglia con doppio schermo</descrizione>
        <prezzo unità="€">1800</prezzo>
        <quantità>5</quantità>
    </prodotto>
</negozio>
